[package]
name = "rustairdrop"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.3"
bs58 = "0.5.1"
solana-client = "1.16.0"
solana-program = "1.16.0"
solana-sdk = "1.16.0"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }

